### ISSUE TITLE
GIPIO to receive .

### ISSUE THREAD

**Issue by Ms3pro** [hankedan000/MegaCAN#4]
Hi! What should I add to the GPIO to receive one 11-bit 8-byte message from MS?

**Comment by hankedan000** [comment]
If you override the [`handleStandard()`](https://github.com/hankedan000/MegaCAN/blob/main/src/MegaCAN_Device.h#L410-L426) method on the `MegaCAN_Device` class then that method will get called each time the MCU receives a standard (11bit ID) CAN frame.

The MegaCan_WithBroadcast class does this to decode some of the Megasquirt broadcast message types.
https://github.com/hankedan000/MegaCAN/blob/main/src/MegaCAN_WithBroadcast.cpp#L19-L81
